// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MoulineWarehouse.Models;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MoulineWarehouse.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MoulineWarehouse.Models.Kit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("InStock")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Planned")
                        .HasColumnType("integer");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.ToTable("Kits");
                });

            modelBuilder.Entity("MoulineWarehouse.Models.KitItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("KitId")
                        .HasColumnType("integer");

                    b.Property<int>("QuantityMm")
                        .HasColumnType("integer");

                    b.Property<int>("ThreadColorId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("KitId");

                    b.HasIndex("ThreadColorId");

                    b.ToTable("KitItems");
                });

            modelBuilder.Entity("MoulineWarehouse.Models.StockItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<int>("ReservedQuantity")
                        .HasColumnType("integer");

                    b.Property<int>("ThreadColorId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ThreadColorId");

                    b.ToTable("StockItems");
                });

            modelBuilder.Entity("MoulineWarehouse.Models.ThreadColor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Manufacturer")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.ToTable("ThreadColors");
                });

            modelBuilder.Entity("MoulineWarehouse.Models.KitItem", b =>
                {
                    b.HasOne("MoulineWarehouse.Models.Kit", "Kit")
                        .WithMany("Items")
                        .HasForeignKey("KitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MoulineWarehouse.Models.ThreadColor", "ThreadColor")
                        .WithMany()
                        .HasForeignKey("ThreadColorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kit");

                    b.Navigation("ThreadColor");
                });

            modelBuilder.Entity("MoulineWarehouse.Models.StockItem", b =>
                {
                    b.HasOne("MoulineWarehouse.Models.ThreadColor", "ThreadColor")
                        .WithMany()
                        .HasForeignKey("ThreadColorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ThreadColor");
                });

            modelBuilder.Entity("MoulineWarehouse.Models.Kit", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
